name: gameboy
description: "Introducing \"gameboy\" – the app that makes you feel like a genius one day and question your life choices the next! 😅 Whether you're cracking Wordsy codes, flexing your vocabulary in BeeWise, or showing off random trivia knowledge, gameboy keeps your neurons firing and your ego in check. Perfect for those who think they’re smart… until they misspell \"yacht.\""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  flutter_bloc: ^8.1.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  equatable: ^2.0.5
  rive: ^0.13.20
  shared_preferences: ^2.5.2
  firebase_remote_config: ^5.5.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/

flutter_gen:
  output: lib/asset_manager/
  line_length: 80
  integrations:
    flutter_svg: true