// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-e4IpvsywVt-86F4qM1kZQaZ7feHsVfU',
    appId: '1:406654937423:web:fe62aa6e7a319a7ad97d3a',
    messagingSenderId: '406654937423',
    projectId: 'gameboy-22c94',
    authDomain: 'gameboy-22c94.firebaseapp.com',
    databaseURL: "https://gameboy-22c94-default-rtdb.firebaseio.com",
    storageBucket: 'gameboy-22c94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBityAfJF8XiTmmJcjZBNJkfBsvtG846WY',
    appId: '1:406654937423:android:c686442d440b51d1d97d3a',
    messagingSenderId: '406654937423',
    projectId: 'gameboy-22c94',
    storageBucket: 'gameboy-22c94.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-e4IpvsywVt-86F4qM1kZQaZ7feHsVfU',
    appId: '1:406654937423:web:7269687a3d7e957dd97d3a',
    messagingSenderId: '406654937423',
    projectId: 'gameboy-22c94',
    authDomain: 'gameboy-22c94.firebaseapp.com',
    storageBucket: 'gameboy-22c94.appspot.com',
  );
}
